<?php

// metanastasis.uninstall
/**
 * Implements hook_uninstall().
 */
function metanastasis_uninstall() {
  // Remove configuration.
  $configuration_installed = \Drupal::service('file_system')
    ->scanDirectory(__DIR__ . '/config/install/', ' /.+(yml)/', ['key' => 'name']);

  foreach ($configuration_installed as $key => $proprieties) {
    Drupal::configFactory()->getEditable($key)->delete();
  }
}

