SELECT
  CONCAT('luogo_',term.tid) AS 'migration_id'
  , term.uuid AS 'uuid'
  , 1 AS 'uid'
  , 'luogo' AS 'type'
  , term.name AS 'title'
  , term.description AS 'field_abstract'
  , 1501 AS 'field_argomenti' -- id aggiornato
  , 1008 AS 'field_tipologia_luogo' -- id aggiornato
  , NULL AS 'field_copertina'
  , NULL AS 'field_video'
  , NULL AS 'field_galleria_immagini'
  , NULL AS 'body_value'
  , NULL AS 'field_luoghi'
  , NULL AS 'field_indirizzo'
  , NULL AS 'field_coordinate_geografiche'
  , NULL AS 'field_orario_pubblico'
  , NULL AS 'field_attributi_luogo'
  , NULL AS 'field_email'
  , NULL AS 'field_telefono'
  , NULL AS 'field_pec'
  , NULL AS 'field_numero_alunni'
  , NULL AS 'field_numero_classi'
  , NULL AS 'field_struttura_esterna'
  , NULL AS 'field_prenotabile'
  , NULL AS 'field_posti'
  , NULL AS 'field_anno_costruzione'
  , NULL AS 'field_numero_piani'
  , NULL AS 'field_codice_identificativo'
  , NULL AS 'field_codice_catastale_comune'
  , 1 AS 'field_uso_scolastico'
  , NULL AS 'field_destinazione_uso'
  , NULL AS 'field_anno_adattamento'
  , NULL AS 'field_superficie_area_totale'
  , NULL AS 'field_superficie_area_libera'
  , NULL AS 'field_volume'
  , NULL AS 'field_sede_legale'
  , NULL AS 'field_codice_meccanografico'
  , NULL AS 'field_codice_fiscale'
  , NULL AS 'field_ipa'
  , NULL AS 'field_codice_cuf'
  , NULL AS 'field_link'
  , 'it' AS 'langcode'
  , 0 AS 'promote'
  , 0 AS 'sticky'
  , 1 AS 'status'
FROM taxonomy_term_data term
  LEFT JOIN field_data_field_codice_meccanografico codice_m ON term.tid = codice_m.entity_id AND codice_m.bundle = 'plesso'
WHERE term.vid = 4
ORDER BY term.weight ASC
;